Short Description
Docker image based on Ubuntu 16.04 that contains the Cuda 8 and OpenCV 3.2 libraries.

Full Description
This Docker image contains the Cuda 8.0 and OpenCV 3.2 (with support for Python 2.7 and Python 3.5) libraries installed upon the official docker image of Ubuntu 16.04.

#### Supported tag and respective Dockerfile
* [**`latest`**, `Dockerfile/Dockerfile.ubuntu16.04-cuda8.0-opencv3.2`](https://github.com/allansp84/Dockerfiles/blob/master/Dockerfile.ubuntu16.04-cuda8.0-opencv3.2)
